// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/check-availability.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
var check_availability_default = defineTool({
  name: "check_availability",
  title: "Check house availability",
  description: "Check whether House La Vita in Kamp Terme 3000 is available between the given check-in and check-out dates (YYYY-MM-DD). Returns available: true only if no booked range overlaps.",
  inputSchema: {
    checkIn: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Check-in date, ISO YYYY-MM-DD"),
    checkOut: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Check-out date, ISO YYYY-MM-DD")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ checkIn, checkOut }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    const inD = /* @__PURE__ */ new Date(checkIn + "T00:00:00");
    const outD = /* @__PURE__ */ new Date(checkOut + "T00:00:00");
    if (!(outD > inD)) {
      return {
        content: [{ type: "text", text: "checkOut must be after checkIn" }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("booked_dates").select("start_date,end_date").lt("start_date", checkOut).gt("end_date", checkIn);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const available = (data ?? []).length === 0;
    const payload = {
      available,
      checkIn,
      checkOut,
      conflictingRanges: data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/calculate-price.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/pricing.ts
function getNightlyRate(checkIn) {
  const month = checkIn.getMonth();
  if (month === 8) {
    return { rate: 95, season: "spring" };
  }
  if (month === 6 || month === 7) {
    return { rate: 100, season: "summer" };
  }
  return { rate: 77, season: "off" };
}
function getLongStayDiscount(nights) {
  if (nights >= 10) return 0.2;
  if (nights >= 7) return 0.15;
  if (nights >= 5) return 0.1;
  if (nights >= 3) return 0.05;
  return 0;
}
function nightsBetween(checkIn, checkOut) {
  const ms = checkOut.getTime() - checkIn.getTime();
  return Math.max(0, Math.round(ms / (1e3 * 60 * 60 * 24)));
}
function computePrice(checkIn, checkOut) {
  if (!checkIn || !checkOut) return null;
  const nights = nightsBetween(checkIn, checkOut);
  if (nights <= 0) return null;
  const { rate, season } = getNightlyRate(checkIn);
  const baseTotal = rate * nights;
  const discountPct = getLongStayDiscount(nights);
  const discountAmount = Math.round(baseTotal * discountPct);
  const finalTotal = baseTotal - discountAmount;
  return {
    nights,
    basePerNight: rate,
    baseTotal,
    discountPct,
    discountAmount,
    finalTotal,
    season
  };
}

// src/lib/mcp/tools/calculate-price.ts
var calculate_price_default = defineTool2({
  name: "calculate_price",
  title: "Calculate stay price",
  description: "Calculate the price for a stay at House La Vita. Uses seasonal nightly rate (June 95\u20AC, July/August 100\u20AC, otherwise 77\u20AC) and long-stay discount (3-4 nights 5%, 5-6 nights 10%, 7-9 nights 15%, 10+ nights 20%). Pets add 5\u20AC/night.",
  inputSchema: {
    checkIn: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    checkOut: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    hasPet: z2.boolean().default(false).describe("Add 5\u20AC/night if a pet is included")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ checkIn, checkOut, hasPet }) => {
    const inD = /* @__PURE__ */ new Date(checkIn + "T00:00:00");
    const outD = /* @__PURE__ */ new Date(checkOut + "T00:00:00");
    const breakdown = computePrice(inD, outD);
    if (!breakdown) {
      return {
        content: [{ type: "text", text: "Invalid date range" }],
        isError: true
      };
    }
    const petFee = hasPet ? 5 * breakdown.nights : 0;
    const finalTotal = breakdown.finalTotal + petFee;
    const payload = { ...breakdown, petFee, finalTotal, currency: "EUR" };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/submit-reservation-inquiry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var submit_reservation_inquiry_default = defineTool3({
  name: "submit_reservation_inquiry",
  title: "Submit reservation inquiry",
  description: "Send a reservation inquiry for House La Vita to the owner (rent@lavitaterme3000.com). Does NOT block the dates \u2014 the owner confirms after receiving a deposit. Guest also gets a localized thank-you email.",
  inputSchema: {
    name: z3.string().min(2).max(120),
    email: z3.string().email(),
    phone: z3.string().max(40).optional(),
    checkIn: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    checkOut: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    guests: z3.number().int().min(1).max(20).optional(),
    hasPet: z3.boolean().default(false),
    message: z3.string().max(2e3).optional(),
    language: z3.enum(["sl", "en", "de", "hr"]).default("en")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input) => {
    const res = await fetch("https://www.lavitaterme3000.com/api/reservation", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input)
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: "Inquiry sent. The owner will contact the guest shortly to confirm and arrange the deposit."
        }
      ],
      structuredContent: { ok: true, response: text }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "house-la-vita-mcp",
  title: "House La Vita \u2013 Terme 3000",
  version: "0.1.0",
  instructions: "Tools for House La Vita, a holiday house in Kamp Terme 3000 (Moravske Toplice, Slovenia). Use `check_availability` to see if a date range is free, `calculate_price` for a seasonal quote with long-stay discount, and `submit_reservation_inquiry` to send a booking request to the owner. Dates are always YYYY-MM-DD. No user authentication required.",
  tools: [check_availability_default, calculate_price_default, submit_reservation_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
